// 30 unique testimonial quotes for videos
const TESTIMONIAL_QUOTES = [
  "Life-changing mentorship",
  "Finally consistent after KCU", 
  "Best investment I ever made",
  "From losing to profitable",
  "Risk management changed everything",
  "The community is incredible",
  "My mindset completely shifted",
  "No more revenge trading",
  "Discipline finally clicked",
  "Breaking even to six figures",
  "Psychology lessons are gold",
  "Structure changed my trading",
  "Went from gambling to strategy",
  "My biggest breakthrough",
  "Execution became effortless",
  "Stopped overtrading completely",
  "Rules over emotions now",
  "Best decision I ever made",
  "Trading like a machine now",
  "From fear to confidence",
  "Risk first, profit second",
  "Consistency over home runs",
  "My trading transformed",
  "No more FOMO trades",
  "Plan the trade, trade the plan",
  "Emotional control unlocked",
  "Size matters more than wins",
  "Process over profits",
  "Mental game is everything",
  "KCU changed my life"
];